-- Detach session_exercises from old system library entries before deleting
UPDATE session_exercises SET library_exercise_id = NULL
WHERE library_exercise_id IN (SELECT id FROM exercise_library WHERE is_system = true);

-- Remove old seed data (only system exercises)
DELETE FROM exercise_library WHERE is_system = true;

-- Re-seed with comprehensive exercise library (118 exercises)
INSERT INTO exercise_library (id, user_id, name, muscle_group, equipment, is_system) VALUES
    -- Chest (18)
    (gen_random_uuid(), NULL, 'Barbell Bench Press',    'Chest', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Incline Dumbbell Press', 'Chest', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Cable Fly',             'Chest', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Dumbbell Bench Press',  'Chest', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Incline Barbell Press', 'Chest', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Decline Bench Press',   'Chest', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Chest Dip',            'Chest', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Push-up',              'Chest', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Pec Deck Machine',     'Chest', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Dumbbell Fly',         'Chest', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Machine Chest Press',  'Chest', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Landmine Press',       'Chest', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Cable Crossover',      'Chest', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Dumbbell Pullover',    'Chest', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Decline Dumbbell Press','Chest', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Wide Push-up',         'Chest', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Decline Push-up',      'Chest', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Archer Push-up',       'Chest', 'Bodyweight',  true),

    -- Back (18)
    (gen_random_uuid(), NULL, 'Pull-up',              'Back', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Barbell Row',          'Back', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Lat Pulldown',         'Back', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Deadlift',             'Back', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Seated Cable Row',     'Back', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Dumbbell Row',         'Back', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'T-Bar Row',            'Back', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Chin-up',              'Back', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Face Pull',            'Back', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Pendlay Row',          'Back', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Machine Row',          'Back', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Straight Arm Pulldown','Back', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Inverted Row',         'Back', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Rack Pull',            'Back', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Renegade Row',         'Back', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Dumbbell Shrug',       'Back', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Dumbbell Reverse Fly', 'Back', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Superman',             'Back', 'Bodyweight',  true),

    -- Legs (21)
    (gen_random_uuid(), NULL, 'Barbell Squat',        'Legs', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Romanian Deadlift',    'Legs', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Leg Press',            'Legs', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Bulgarian Split Squat','Legs', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Leg Extension',        'Legs', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Leg Curl',             'Legs', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Walking Lunge',        'Legs', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Goblet Squat',         'Legs', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Hip Thrust',           'Legs', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Front Squat',          'Legs', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Hack Squat',           'Legs', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Standing Calf Raise',  'Legs', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Sumo Deadlift',        'Legs', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Dumbbell Step-up',     'Legs', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Glute Bridge',         'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Bodyweight Squat',     'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Pistol Squat',         'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Jump Squat',           'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Wall Sit',             'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Reverse Lunge',        'Legs', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Dumbbell Romanian Deadlift', 'Legs', 'Dumbbells', true),

    -- Shoulders (17)
    (gen_random_uuid(), NULL, 'Overhead Press',       'Shoulders', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Lateral Raise',        'Shoulders', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Dumbbell Shoulder Press','Shoulders','Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Arnold Press',         'Shoulders', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Front Raise',          'Shoulders', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Reverse Fly',          'Shoulders', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Cable Lateral Raise',  'Shoulders', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Upright Row',          'Shoulders', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Machine Shoulder Press','Shoulders', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Rear Delt Fly Machine','Shoulders', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Push Press',           'Shoulders', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Lu Raise',             'Shoulders', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Pike Push-up',         'Shoulders', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Handstand Push-up',    'Shoulders', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Wall Walk',            'Shoulders', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Bodyweight Y Raise',   'Shoulders', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Cable Face Pull',      'Shoulders', 'Cable',      true),

    -- Arms (19)
    (gen_random_uuid(), NULL, 'Barbell Curl',         'Arms', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Dumbbell Curl',        'Arms', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Tricep Pushdown',      'Arms', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Hammer Curl',          'Arms', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Skull Crusher',        'Arms', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Preacher Curl',        'Arms', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Overhead Tricep Extension','Arms','Dumbbells',true),
    (gen_random_uuid(), NULL, 'Cable Curl',           'Arms', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Tricep Dip',           'Arms', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Concentration Curl',   'Arms', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Close-Grip Bench Press','Arms', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Incline Dumbbell Curl','Arms', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Tricep Kickback',      'Arms', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Wrist Curl',           'Arms', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Diamond Push-up',      'Arms', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Bench Dip',            'Arms', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Chin-up Close Grip',   'Arms', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Overhead Cable Extension','Arms','Cable',     true),
    (gen_random_uuid(), NULL, 'Dumbbell Zottman Curl','Arms', 'Dumbbells',  true),

    -- Core (14)
    (gen_random_uuid(), NULL, 'Plank',                'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Hanging Leg Raise',    'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Cable Crunch',         'Core', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Ab Wheel Rollout',     'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Russian Twist',        'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Bicycle Crunch',       'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Mountain Climber',     'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Dead Bug',             'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'V-up',                 'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Pallof Press',         'Core', 'Cable',      true),
    (gen_random_uuid(), NULL, 'Decline Sit-up',       'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Side Plank',           'Core', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Dumbbell Woodchop',    'Core', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Weighted Sit-up',      'Core', 'Dumbbells',  true),

    -- Other (11)
    (gen_random_uuid(), NULL, 'Farmer''s Walk',       'Other', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Battle Ropes',         'Other', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Box Jump',             'Other', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Kettlebell Swing',     'Other', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Sled Push',            'Other', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Turkish Get-up',       'Other', 'Dumbbells',  true),
    (gen_random_uuid(), NULL, 'Clean and Press',      'Other', 'Barbell',    true),
    (gen_random_uuid(), NULL, 'Burpee',               'Other', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Bear Crawl',           'Other', 'Bodyweight',  true),
    (gen_random_uuid(), NULL, 'Rowing Machine',       'Other', 'Machine',    true),
    (gen_random_uuid(), NULL, 'Jumping Jack',         'Other', 'Bodyweight',  true);
